// ================================================================
// drivers.js — F1 Driver Database
// To add a photo set: photo: "public/filename.png"
// ================================================================

// ============================================================
// DATABASE — adaugă/modifică șoferii aici
// ============================================================
const DRIVERS = [
  { id: 1, name: "Lewis Hamilton", nationality: "British", flag: "🇬🇧", team: "Ferrari", teamColor: "#E8002D", born: "80s", wins: 105, poles: 104, photo: "public/photos/lewis-hamilton.png" },
  { id: 2, name: "Max Verstappen", nationality: "Dutch", flag: "🇳🇱", team: "Red Bull", teamColor: "#3671C6", born: "90s", wins: 71, poles: 48, photo: "public/photos/max-verstappen.png" },
  { id: 3, name: "Valtteri Bottas", nationality: "Finnish", flag: "🇫🇮", team: "Cadillac", teamColor: "#888", born: "80s", wins: 10, poles: 20, photo: "public/photos/valtteri-bottas.png" },
  { id: 4, name: "Sergio Perez", nationality: "Mexican", flag: "🇲🇽", team: "Cadillac", teamColor: "#888", born: "90s", wins: 6, poles: 3, photo: "public/photos/sergio-perez.png" },
  { id: 5, name: "Charles Leclerc", nationality: "Monegasque", flag: "🇲🇨", team: "Ferrari", teamColor: "#E8002D", born: "90s", wins: 8, poles: 27, photo: "public/photos/charles-leclerc.png" },
  { id: 6, name: "Carlos Sainz Jr.", nationality: "Spanish", flag: "🇪🇸", team: "Williams", teamColor: "#64C4FF", born: "90s", wins: 4, poles: 6, photo: "public/photos/carlos-sainz-jr.png" },
  { id: 7, name: "Lando Norris", nationality: "British", flag: "🇬🇧", team: "McLaren", teamColor: "#FF8000", born: "90s", wins: 11, poles: 16, photo: "public/photos/lando-norris.png" },
  { id: 8, name: "Daniel Ricciardo", nationality: "Australian", flag: "🇦🇺", team: "Retired", teamColor: "#555", born: "80s", wins: 8, poles: 3, photo: "public/photos/daniel-ricciardo.png" },
  { id: 9, name: "Pierre Gasly", nationality: "French", flag: "🇫🇷", team: "Alpine", teamColor: "#0093CC", born: "90s", wins: 1, poles: 0, photo: "public/photos/pierre-gasly.png" },
  { id: 10, name: "Yuki Tsunoda", nationality: "Japanese", flag: "🇯🇵", team: "Reserve", teamColor: "#3671C6", born: "00s", wins: 0, poles: 0, photo: "public/photos/yuki-tsunoda.png" },
  { id: 11, name: "Fernando Alonso", nationality: "Spanish", flag: "🇪🇸", team: "Aston Martin", teamColor: "#358C75", born: "80s", wins: 32, poles: 22, photo: "public/photos/fernando-alonso.png" },
  { id: 12, name: "Esteban Ocon", nationality: "French", flag: "🇫🇷", team: "Haas", teamColor: "#B6BABD", born: "90s", wins: 1, poles: 0, photo: "public/photos/esteban-ocon.png" },
  { id: 13, name: "Sebastian Vettel", nationality: "German", flag: "🇩🇪", team: "Retired", teamColor: "#555", born: "80s", wins: 53, poles: 57, photo: "public/photos/sebastian-vettel.png" },
  { id: 14, name: "Lance Stroll", nationality: "Canadian", flag: "🇨🇦", team: "Aston Martin", teamColor: "#358C75", born: "90s", wins: 0, poles: 1, photo: "public/photos/lance-stroll.png" },
  { id: 15, name: "Kimi Raikkonen", nationality: "Finnish", flag: "🇫🇮", team: "Retired", teamColor: "#555", born: "70s", wins: 21, poles: 18, photo: "public/photos/kimi-raikkonen.png" },
  { id: 16, name: "George Russell", nationality: "British", flag: "🇬🇧", team: "Mercedes", teamColor: "#27F4D2", born: "90s", wins: 6, poles: 8, photo: "public/photos/george-russell.png" },
  { id: 17, name: "Mick Schumacher", nationality: "German", flag: "🇩🇪", team: "Haas", teamColor: "#B6BABD", born: "90s", wins: 0, poles: 0, photo: "public/photos/mick-schumacher.png" },
  { id: 19, name: "Alexander Albon", nationality: "Thai", flag: "🇹🇭", team: "Williams", teamColor: "#64C4FF", born: "90s", wins: 0, poles: 0, photo: "public/photos/alexander-albon.png" },
  { id: 20, name: "Kevin Magnussen", nationality: "Danish", flag: "🇩🇰", team: "Haas", teamColor: "#B6BABD", born: "90s", wins: 0, poles: 1, photo: "public/photos/kevin-magnussen.png" },
  { id: 21, name: "Guanyu Zhou", nationality: "Chinese", flag: "🇨🇳", team: "Reserve", teamColor: "#888", born: "90s", wins: 0, poles: 0, photo: "public/photos/guanyu-zhou.png" },
  { id: 22, name: "Oscar Piastri", nationality: "Australian", flag: "🇦🇺", team: "McLaren", teamColor: "#FF8000", born: "00s", wins: 9, poles: 6, photo: "public/photos/oscar-piastri.png" },
  { id: 23, name: "Nicholas Latifi", nationality: "Canadian", flag: "🇨🇦", team: "Retired", teamColor: "#555", born: "90s", wins: 0, poles: 0, photo: "public/photos/nicholas-latifi.png" },
  { id: 24, name: "Nyck de Vries", nationality: "Dutch", flag: "🇳🇱", team: "AlphaTauri", teamColor: "#2B4562", born: "90s", wins: 0, poles: 0, photo: "public/photos/nyck-de-vries.png" },
  { id: 25, name: "Logan Sargeant", nationality: "American", flag: "🇺🇸", team: "Williams", teamColor: "#64C4FF", born: "00s", wins: 0, poles: 0, photo: "public/photos/logan-sargeant.png" },
  { id: 26, name: "Liam Lawson", nationality: "New Zealander", flag: "🇳🇿", team: "Racing Bulls", teamColor: "#6692FF", born: "00s", wins: 0, poles: 0, photo: "public/photos/liam-lawson.png" },
  { id: 27, name: "Oliver Bearman", nationality: "British", flag: "🇬🇧", team: "Haas", teamColor: "#B6BABD", born: "00s", wins: 0, poles: 0, photo: "public/photos/oliver-bearman.png" },
  { id: 28, name: "Franco Colapinto", nationality: "Argentinian", flag: "🇦🇷", team: "Alpine", teamColor: "#0093CC", born: "00s", wins: 0, poles: 0, photo: "public/photos/franco-colapinto.png" },
  { id: 29, name: "Kimi Antonelli", nationality: "Italian", flag: "🇮🇹", team: "Mercedes", teamColor: "#27F4D2", born: "00s", wins: 2, poles: 2, photo: "public/photos/kimi-antonelli.png" },
  { id: 30, name: "Jack Doohan", nationality: "Australian", flag: "🇦🇺", team: "Reserve", teamColor: "#B6BABD", born: "00s", wins: 0, poles: 0, photo: "public/photos/jack-doohan.png" },
  { id: 31, name: "Michael Schumacher", nationality: "German", flag: "🇩🇪", team: "Retired", teamColor: "#555", born: "60s", wins: 91, poles: 68, photo: "public/photos/michael-schumacher.png" },
  { id: 32, name: "Ayrton Senna", nationality: "Brazilian", flag: "🇧🇷", team: "Retired", teamColor: "#555", born: "60s", wins: 41, poles: 65, photo: "public/photos/ayrton-senna.png" },
  { id: 33, name: "Alain Prost", nationality: "French", flag: "🇫🇷", team: "Retired", teamColor: "#555", born: "50s", wins: 51, poles: 33, photo: "public/photos/alain-prost.png" },
  { id: 34, name: "Niki Lauda", nationality: "Austrian", flag: "🇦🇹", team: "Retired", teamColor: "#555", born: "40s", wins: 25, poles: 24, photo: "public/photos/niki-lauda.png" },
  { id: 35, name: "Juan Manuel Fangio", nationality: "Argentinian", flag: "🇦🇷", team: "Retired", teamColor: "#555", born: "1910s", wins: 24, poles: 29, photo: "public/photos/juan-manuel-fangio.png" },
  { id: 36, name: "Nelson Piquet", nationality: "Brazilian", flag: "🇧🇷", team: "Retired", teamColor: "#555", born: "50s", wins: 23, poles: 24, photo: "public/photos/nelson-piquet.png" },
  { id: 37, name: "Nigel Mansell", nationality: "British", flag: "🇬🇧", team: "Retired", teamColor: "#555", born: "50s", wins: 31, poles: 32, photo: "public/photos/nigel-mansell.png" },
  { id: 38, name: "Jackie Stewart", nationality: "British", flag: "🇬🇧", team: "Retired", teamColor: "#555", born: "30s", wins: 27, poles: 17, photo: "public/photos/jackie-stewart.png" },
  { id: 39, name: "Gilles Villeneuve", nationality: "Canadian", flag: "🇨🇦", team: "Retired", teamColor: "#555", born: "50s", wins: 6, poles: 2, photo: "public/photos/gilles-villeneuve.png" },
  { id: 40, name: "Jim Clark", nationality: "British", flag: "🇬🇧", team: "Retired", teamColor: "#555", born: "30s", wins: 25, poles: 33, photo: "public/photos/jim-clark.png" },
  { id: 41, name: "Jenson Button", nationality: "British", flag: "🇬🇧", team: "Retired", teamColor: "#555", born: "80s", wins: 15, poles: 8, photo: "public/photos/jenson-button.png" },
  { id: 42, name: "Rubens Barrichello", nationality: "Brazilian", flag: "🇧🇷", team: "Retired", teamColor: "#555", born: "70s", wins: 11, poles: 14, photo: "public/photos/rubens-barrichello.png" },
  { id: 43, name: "Nico Rosberg", nationality: "German", flag: "🇩🇪", team: "Retired", teamColor: "#555", born: "80s", wins: 23, poles: 30, photo: "public/photos/nico-rosberg.png" },
  { id: 44, name: "Felipe Massa", nationality: "Brazilian", flag: "🇧🇷", team: "Retired", teamColor: "#555", born: "80s", wins: 11, poles: 16, photo: "public/photos/felipe-massa.png" },
  { id: 45, name: "Graham Hill", nationality: "British", flag: "🇬🇧", team: "Retired", teamColor: "#555", born: "20s", wins: 14, poles: 13, photo: "public/photos/graham-hill.png" },
  { id: 46, name: "Emerson Fittipaldi", nationality: "Brazilian", flag: "🇧🇷", team: "Retired", teamColor: "#555", born: "40s", wins: 14, poles: 6, photo: "public/photos/emerson-fittipaldi.png" },
  { id: 47, name: "James Hunt", nationality: "British", flag: "🇬🇧", team: "Retired", teamColor: "#555", born: "40s", wins: 10, poles: 14, photo: "public/photos/james-hunt.png" },
  { id: 48, name: "Mario Andretti", nationality: "American", flag: "🇺🇸", team: "Retired", teamColor: "#555", born: "40s", wins: 12, poles: 18, photo: "public/photos/mario-andretti.png" },
  { id: 49, name: "Jack Brabham", nationality: "Australian", flag: "🇦🇺", team: "Retired", teamColor: "#555", born: "20s", wins: 14, poles: 13, photo: "public/photos/jack-brabham.png" },
  { id: 50, name: "Denny Hulme", nationality: "New Zealander", flag: "🇳🇿", team: "Retired", teamColor: "#555", born: "30s", wins: 8, poles: 1, photo: "public/photos/denny-hulme.png" },
  { id: 51, name: "Damon Hill", nationality: "British", flag: "🇬🇧", team: "Retired", teamColor: "#555", born: "60s", wins: 22, poles: 20, photo: "public/photos/damon-hill.png" },
  { id: 52, name: "Mika Hakkinen", nationality: "Finnish", flag: "🇫🇮", team: "Retired", teamColor: "#555", born: "60s", wins: 20, poles: 26, photo: "public/photos/mika-hakkinen.png" },
  { id: 53, name: "David Coulthard", nationality: "British", flag: "🇬🇧", team: "Retired", teamColor: "#555", born: "70s", wins: 13, poles: 12, photo: "public/photos/david-coulthard.png" },
  { id: 54, name: "Keke Rosberg", nationality: "Finnish", flag: "🇫🇮", team: "Retired", teamColor: "#555", born: "50s", wins: 5, poles: 5, photo: "public/photos/keke-rosberg.png" },
  { id: 55, name: "Antonio Giovinazzi", nationality: "Italian", flag: "🇮🇹", team: "Reserve", teamColor: "#E8002D", born: "90s", wins: 0, poles: 0, photo: "public/photos/antonio-giovinazzi.png" },
  { id: 56, name: "Alberto Ascari", nationality: "Italian", flag: "🇮🇹", team: "Retired", teamColor: "#555", born: "1910s", wins: 13, poles: 14, photo: "public/photos/alberto-ascari.png" },
  { id: 57, name: "Nino Farina", nationality: "Italian", flag: "🇮🇹", team: "Retired", teamColor: "#555", born: "00s", wins: 5, poles: 5, photo: "public/photos/nino-farina.png" },
  { id: 58, name: "Jochen Rindt", nationality: "Austrian", flag: "🇦🇹", team: "Retired", teamColor: "#555", born: "40s", wins: 6, poles: 10, photo: "public/photos/jochen-rindt.png" },
  { id: 59, name: "John Surtees", nationality: "British", flag: "🇬🇧", team: "Retired", teamColor: "#555", born: "30s", wins: 6, poles: 8, photo: "public/photos/john-surtees.png" },
  { id: 60, name: "Jacques Villeneuve", nationality: "Canadian", flag: "🇨🇦", team: "Retired", teamColor: "#555", born: "70s", wins: 11, poles: 13, photo: "public/photos/jacques-villeneuve.png" },
  { id: 61, name: "Romain Grosjean", nationality: "French", flag: "🇫🇷", team: "Retired", teamColor: "#555", born: "80s", wins: 0, poles: 0, photo: "public/photos/romain-grosjean.png" },
  { id: 62, name: "Ralf Schumacher", nationality: "German", flag: "🇩🇪", team: "Retired", teamColor: "#555", born: "70s", wins: 6, poles: 6, photo: "public/photos/ralf-schumacher.png" },
  { id: 63, name: "Heinz-Harald Frentzen", nationality: "German", flag: "🇩🇪", team: "Retired", teamColor: "#555", born: "60s", wins: 3, poles: 2, photo: "public/photos/heinz-harald-frentzen.png" },
  { id: 64, name: "Giancarlo Fisichella", nationality: "Italian", flag: "🇮🇹", team: "Retired", teamColor: "#555", born: "70s", wins: 3, poles: 4, photo: "public/photos/giancarlo-fisichella.png" },
  { id: 65, name: "Mark Webber", nationality: "Australian", flag: "🇦🇺", team: "Retired", teamColor: "#555", born: "70s", wins: 9, poles: 13, photo: "public/photos/mark-webber.png" },
  { id: 66, name: "Daniil Kvyat", nationality: "Russian", flag: "🇷🇺", team: "AlphaTauri", teamColor: "#2B4562", born: "90s", wins: 0, poles: 0, photo: "public/photos/daniil-kvyat.png" },
  { id: 67, name: "Pastor Maldonado", nationality: "Venezuelan", flag: "🇻🇪", team: "Retired", teamColor: "#555", born: "80s", wins: 1, poles: 1, photo: "public/photos/pastor-maldonado.png" },
  { id: 68, name: "Carlos Reutemann", nationality: "Argentinian", flag: "🇦🇷", team: "Retired", teamColor: "#555", born: "40s", wins: 12, poles: 6, photo: "public/photos/carlos-reutemann.png" },
  { id: 69, name: "Ronnie Peterson", nationality: "Swedish", flag: "🇸🇪", team: "Retired", teamColor: "#555", born: "40s", wins: 10, poles: 14, photo: "public/photos/ronnie-peterson.png" },
  { id: 70, name: "Jacky Ickx", nationality: "Belgian", flag: "🇧🇪", team: "Retired", teamColor: "#555", born: "40s", wins: 8, poles: 13, photo: "public/photos/jacky-ickx.png" },
  { id: 71, name: "René Arnoux", nationality: "French", flag: "🇫🇷", team: "Retired", teamColor: "#555", born: "40s", wins: 7, poles: 18, photo: "public/photos/rene-arnoux.png" },
  { id: 72, name: "Juan Pablo Montoya", nationality: "Colombian", flag: "🇨🇴", team: "Retired", teamColor: "#555", born: "70s", wins: 7, poles: 13, photo: "public/photos/juan-pablo-montoya.png" },
  { id: 73, name: "Bruce McLaren", nationality: "New Zealander", flag: "🇳🇿", team: "Retired", teamColor: "#555", born: "30s", wins: 4, poles: 0, photo: "public/photos/bruce-mclaren.png" },
  { id: 74, name: "Heikki Kovalainen", nationality: "Finnish", flag: "🇫🇮", team: "Retired", teamColor: "#555", born: "80s", wins: 1, poles: 1, photo: "public/photos/heikki-kovalainen.png" },
  { id: 75, name: "Jos Verstappen", nationality: "Dutch", flag: "🇳🇱", team: "Retired", teamColor: "#555", born: "70s", wins: 0, poles: 0, photo: "public/photos/jos-verstappen.png" },
  { id: 76, name: "Jarno Trulli", nationality: "Italian", flag: "🇮🇹", team: "Retired", teamColor: "#555", born: "70s", wins: 1, poles: 4, photo: "public/photos/jarno-trulli.png" },
  { id: 77, name: "Isack Hadjar", nationality: "French", flag: "🇫🇷", team: "Red Bull", teamColor: "#3671C6", born: "00s", wins: 0, poles: 0, photo: "public/photos/isack-hadjar.png" },
  { id: 78, name: "Gabriel Bortoleto", nationality: "Brazilian", flag: "🇧🇷", team: "Audi", teamColor: "#C8410A", born: "00s", wins: 0, poles: 0, photo: "public/photos/gabriel-bortoleto.png" },
  { id: 79, name: "Nico Hulkenberg", nationality: "German", flag: "🇩🇪", team: "Audi", teamColor: "#C8410A", born: "80s", wins: 0, poles: 1, photo: "public/photos/nico-hulkenberg.png" },
  { id: 80, name: "Jody Scheckter", nationality: "South African", flag: "🇿🇦", team: "Retired", teamColor: "#555", born: "50s", wins: 10, poles: 3, photo: "public/photos/jody-scheckter.png" },
  { id: 81, name: "Robert Kubica", nationality: "Polish", flag: "🇵🇱", team: "Retired", teamColor: "#555", born: "80s", wins: 1, poles: 1, photo: "public/photos/robert-kubica.png" },
];

// ============================================================
